[package]
name = "eigensdk-services-avsregistry"
description = "Eigen Layer SDK services avsregistry"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
ethers.workspace = true
eth-keystore = "0.5.0"
thiserror.workspace = true
eigensdk-client-avsregistry.workspace = true
eigensdk-services-operatorsinfo.workspace = true
eigensdk-types.workspace = true
eigensdk-contract-bindings.workspace = true
eigensdk-crypto-bls.workspace = true
eigensdk-crypto-bn254.workspace = true