[package]
name = "eigen-metrics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
eigen-crypto-bls.workspace = true
eigen-crypto-bn254.workspace = true
eigen-metrics-derive.workspace = true
metrics.workspace = true

#prometheus
metrics-exporter-prometheus.workspace = true
eigen-metrics-collectors-economic.workspace = true 
reqwest = "0.12.4"
eyre.workspace = true

#http
hyper.workspace = true

#tokio
tokio.workspace = true