[workspace]
members = [ "crates/chainio/clients/avsregistry/",
"crates/chainio/clients/elcontracts/",
"crates/chainio/clients/eth/",
"crates/chainio/clients/fireblocks/",
"crates/contracts/bindings/",
"crates/chainio/utils/",
"crates/crypto/bn254/",
"crates/utils/",
"crates/crypto/bls/",
"crates/metrics/collectors/economic/",
"crates/metrics/collectors/rpc_calls/",
"crates/services/avsregistry/",
"crates/services/bls_aggregation/",
"crates/services/operatorsinfo/",
"crates/types/",
"crates/metrics/",
"crates/types/"]

resolver = "2"

[workspace.package]
version = "0.0.1-alpha"
edition = "2021"
authors = ["Eigen Layer contributors"]
rust-version = "1.76"
repository = "https://github.com/anjaneyalabs/eigensdk-rs"
homepage = ""
license-file = "LICENSE.txt"


[workspace.lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"
rust.unused_must_use = "deny"
rust.rust_2018_idioms = "deny"
rustdoc.all = "warn"


[workspace.dependencies]
ethers =  "2.0.14"
ark-ff = "0.4.0"
reth = {git = "https://github.com/paradigmxyz/reth"}
prometheus-client = "0.22.2"
bn254 = {git = "https://github.com/sedaprotocol/bn254"}
eigensdk-metrics = {version = "0.0.1-alpha",  path = "crates/metrics/"}
serde = {version = "1.0.197" , features = ["derive"]}
eigensdk-chainio-utils = {path = "crates/chainio/utils/"}
eigensdk-client-avsregistry = {path = "crates/chainio/clients/avsregistry"}
eigensdk-client-elcontracts = {version = "0.0.1-alpha",path = "crates/chainio/clients/elcontracts"}
eigensdk-client-eth = {version = "0.0.1-alpha",path = "crates/chainio/clients/eth"}
eigensdk-client-fireblocks = {version = "0.0.1-alpha",path = "crates/chainio/clients/fireblocks"}
eigensdk-contract-bindings = {version = "0.0.1-alpha", path = "crates/contracts/bindings/"}
eigensdk-types = {version = "0.0.1-alpha",path = "crates/types/"}
eigensdk-crypto-bls = {path = "crates/crypto/bls/"}
eigensdk-crypto-bn254 = {version = "0.0.1-alpha",path = "crates/crypto/bn254/"}
eigensdk-utils = {version = "0.0.1-alpha" , path = "crates/utils/"}
eigensdk-metrics-collectors-economic = {version = "0.0.1-alpha",path = "crates/metrics/collectors/economic"}
eigensdk-metrics-collectors-rpc-calls = {version = "0.0.1-alpha",path = "crates/metrics/collectors/rpc_calls"}
eigensdk-services-avsregistry = {path = "crates/services/avsregistry"}
eigensdk-services-bls_aggregation = {path = "crates/services/bls_aggregation"}
eigensdk-services-operatorsinfo = {path = "crates/services/operatorsinfo"}
tokio = {version = "1.37.0" , features = ["test-util", "full","sync"] }

thiserror = "1.0"
tracing = "0.1.40"



#misc 
parking_lot = "0.12"

#alloy
alloy-chains = "0.1.15"
alloy-primitives = "0.7.2"
alloy-dyn-abi = "0.7.2"
alloy-sol-types = "0.7.2"
alloy-rlp = "0.3.4"
alloy-trie = "0.3.1"
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-rpc-types-anvil = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-rpc-types-trace = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-rpc-types-engine = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-genesis = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-node-bindings = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-provider = { git = "https://github.com/alloy-rs/alloy", rev = "af788af", default-features = false, features = [
    "reqwest",
] }
alloy-transport-http = {git = "https://github.com/alloy-rs/alloy", rev = "af788af"}
alloy-eips = { git = "https://github.com/alloy-rs/alloy", default-features = false, rev = "af788af" }
alloy-signer = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-signer-wallet = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-network = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-consensus = { git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-contract = {git = "https://github.com/alloy-rs/alloy", rev = "af788af" }
alloy-transport =  {git = "https://github.com/alloy-rs/alloy", rev = "af788af"}
alloy-transport-ws = {git = "https://github.com/alloy-rs/alloy", rev = "af788af"}