[workspace]
members = [ "crates/chainio/clients/avsregistry",
"crates/chainio/clients/elcontracts/",
"crates/chainio/clients/eth/",
"crates/chainio/clients/fireblocks/",
"crates/chainio/clients/builder/",
"crates/chainio/clients/wallet/",
"crates/contracts/",
"crates/logging/",
"crates/metrics/",
"crates/services/",
"crates/signer/"]

resolver = "2"

[workspace.package]
version = "0.0.1-alpha"
edition = "2021"
rust-version = "1.75"
repository = "https://github.com/anjaneyalabs/eigensdk-rs"

[workspace.lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"
rust.unused_must_use = "deny"
rust.rust_2018_idioms = "deny"
rustdoc.all = "warn"


[workspace.dependencies]
reth = {git = "https://github.com/paradigmxyz/reth"}
prometheus-client = "0.22.2"
bn254 = {git = "https://github.com/sedaprotocol/bn254"}
eigensdk-metrics = {path = "crates/metrics"}
serde = {version = "1.0.197" , features = ["derive"]}
alloy-primitives = "0.6.4"
eigensdk-client-avsregistry = {path = "crates/chainio/clients/avsregistry"}
eigensdk-client-builder = {path = "crates/chainio/clients/builder"}
eigensdk-client-elcontracts = {path = "crates/chainio/clients/elcontracts"}
eigensdk-client-eth = {path = "crates/chainio/clients/eth"}
eigensdk-client-fireblocks = {path = "crates/chainio/clients/fireblocks"}
eigensdk-client-wallet = {path = "crates/chainio/clients/wallet"}
eigensdk-contracts = {path  = "crates/contracts"}
eigensdk-logging = {path = "crates/logging"}
alloy-sol-types = {version = "0.6.4", features = ["json"]}
