[workspace]
members = [ "crates/chainio/clients/avsregistry/",
"crates/chainio/clients/elcontracts/",
"crates/chainio/clients/eth/",
"crates/chainio/clients/fireblocks/",
"crates/chainio/clients/builder/",
"crates/chainio/clients/wallet/",
"crates/contracts/bindings/",
"crates/signerv2/",
"crates/chainio/utils/",
"crates/crypto/bn254/",
"crates/utils/",
"crates/crypto/bls/",
"crates/metrics/collectors/economic/",
"crates/metrics/collectors/rpc_calls/",
"crates/services/avsregistry/",
"crates/services/bls_aggregation/",
"crates/services/operatorsinfo/",
"crates/types/",
"crates/metrics/",
"crates/chainio/txmgr/",
"crates/types/",
"crates/signer/"]

resolver = "2"

[workspace.package]
version = "0.0.1-alpha"
edition = "2021"
authors = ["Eigen Layer contributors"]
rust-version = "1.76"
repository = "https://github.com/anjaneyalabs/eigensdk-rs"
homepage = ""
license-file = "LICENSE.txt"


[workspace.lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"
rust.unused_must_use = "deny"
rust.rust_2018_idioms = "deny"
rustdoc.all = "warn"


[workspace.dependencies]
ethers =  "2.0.14"
ark-ff = "0.4.0"
ethers-providers ="2.0.14"
ethers-core = "2.0.14"
reth = {git = "https://github.com/paradigmxyz/reth"}
prometheus-client = "0.22.2"
bn254 = {git = "https://github.com/sedaprotocol/bn254"}
eigensdk-metrics = {version = "0.0.1-alpha",  path = "crates/metrics/"}
serde = {version = "1.0.197" , features = ["derive"]}
eigensdk-chainio-utils = {version = "0.0.1-alpha", path = "crates/chainio/utils/"}
alloy-primitives = "0.7.0"
eigensdk-client-avsregistry = {path = "crates/chainio/clients/avsregistry"}
eigensdk-client-builder = {version = "0.0.1-alpha",path = "crates/chainio/clients/builder"}
eigensdk-client-elcontracts = {version = "0.0.1-alpha",path = "crates/chainio/clients/elcontracts"}
eigensdk-client-eth = {version = "0.0.1-alpha",path = "crates/chainio/clients/eth"}
eigensdk-client-fireblocks = {version = "0.0.1-alpha",path = "crates/chainio/clients/fireblocks"}
eigensdk-client-wallet = {version = "0.0.1-alpha",path = "crates/chainio/clients/wallet"}
eigensdk-contract-bindings = {version = "0.0.1-alpha", path = "crates/contracts/bindings/"}
eigensdk-types = {version = "0.0.1-alpha",path = "crates/types/"}
eigensdk-crypto-bls = {version = "0.0.1-alpha",path = "crates/crypto/bls/"}
eigensdk-crypto-bn254 = {version = "0.0.1-alpha",path = "crates/crypto/bn254/"}
eigensdk-txmgr = {version = "0.0.1-alpha",path = "crates/chainio/txmgr/"}
alloy-sol-types = {git = "https://github.com/alloy-rs/core", rev = "5edbf5e17f0874c2870c7bba43ae063081adabb5", features = ["json"]}
alloy-contract = { git = "https://github.com/alloy-rs/alloy", rev = "818b3e9692f2a207e456653a67aa8956fe1518a9", path = "crates/contract" }
alloy-provider = { git = "https://github.com/alloy-rs/alloy", rev = "818b3e9692f2a207e456653a67aa8956fe1518a9"}
alloy-network = { git = "https://github.com/alloy-rs/alloy", rev = "818b3e9692f2a207e456653a67aa8956fe1518a9"}
eigensdk-signerv2 = {version = "0.0.1-alpha",path = "crates/signerv2/"}
eigensdk-utils = {version = "0.0.1-alpha" , path = "crates/utils/"}
ethers-signers = "2.0.14"
eigensdk-metrics-collectors-economic = {version = "0.0.1-alpha",path = "crates/metrics/collectors/economic"}
eigensdk-metrics-collectors-rpc-calls = {version = "0.0.1-alpha",path = "crates/metrics/collectors/rpc_calls"}
eigensdk-services-avsregistry = {path = "crates/services/avsregistry"}
eigensdk-services-bls_aggregation = {path = "crates/services/bls_aggregation"}
eigensdk-services-operatorsinfo = {path = "crates/services/operatorsinfo"}
tokio = {version = "1.37.0" , features = ["test-util", "full","sync"] }

thiserror = "1.0"
tracing = "0.1.40"