[package]
name = "eigensdk-client-eth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
# reth.workspace = true
ethers.workspace = true
eigensdk-metrics-collectors-rpc-calls.workspace = true