[package]
name = "eigensdk-contracts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
alloy-sol-macro = "0.6.4"
alloy-sol-types = {version = "0.6.4", features = ["json"]}

