[package]
name = "eigensdk-metrics-collectors-economic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
# reth.workspace = true
ethers-core.workspace = true
ethers.workspace = true
ethers-signers.workspace = true
eigensdk-client-elcontracts.workspace = true
eigensdk-client-avsregistry.workspace = true
