[package]
name = "eigen-services-blsaggregation"
description = "Eigen Layer SDK services blsaggregation"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
ethers.workspace = true
eth-keystore = "0.5.0"
thiserror.workspace = true
eigen-types.workspace = true
eigen-crypto-bls.workspace = true
eigen-services-avsregistry.workspace = true
parking_lot.workspace = true
tokio = {workspace = true, features = ["full"]}
eigen-crypto-bn254.workspace = true
alloy-primitives.workspace = true