[package]
name = "eigensdk-services-blsaggregation"
description = "Eigen Layer SDK services blsaggregation"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
ethers.workspace = true
eth-keystore = "0.5.0"
thiserror.workspace = true
eigensdk-types.workspace = true
eigensdk-crypto-bls.workspace = true
eigensdk-services-avsregistry.workspace = true
parking_lot.workspace = true
eigensdk-crypto-bn254.workspace = true
alloy-primitives.workspace = true
tokio = { workspace = true, features = ["full"] }
