[package]
name = "eigensdk-services-blsaggregation"
description = "Eigen Layer SDK services blsaggregation"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
ethers-core.workspace = true
ethers.workspace = true
ethers-signers.workspace = true
eth-keystore = "0.5.0"
thiserror.workspace = true
eigensdk-types.workspace = true
eigensdk-crypto-bls.workspace = true