[package]
name = "eigensdk-client-elcontracts"
description = "Eigen Layer core contracts sdk"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
# reth.workspace = true
eigensdk-contract-bindings.workspace = true
ethers-providers.workspace=true
ethers-core.workspace=true
ark-bn254 = "0.4.0"
ark-ff = "0.4.0"
eigensdk-txmgr.workspace=true
eigensdk-types.workspace=true
ethers.workspace = true
thiserror.workspace = true
tracing.workspace = true