[package]
name = "eigensdk-contract-bindings"
description = "Eigen Layer contract bindings"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
ethers = "2.0.14"


