[package]
name = "eigen-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
alloy-network.workspace = true
alloy-provider.workspace = true
alloy-transport-http.workspace = true
alloy-signer-wallet.workspace = true
reqwest.workspace = true