[package]
name = "eigensdk-client-wallet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
# reth.workspace = true
serde.workspace = true
alloy-primitives.workspace = true