[package]
name = "eigensdk-types"
description = "Eigen Layer types "

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
ethers.workspace = true
num-bigint = "0.4.4"
eigensdk-crypto-bls.workspace = true
eigensdk-contract-bindings.workspace = true