[package]
name = "eigensdk-services-operatorsinfo"
description = "Eigen Layer SDK services operatorsinfo"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
ethers-core.workspace = true
ethers.workspace = true
ethers-signers.workspace = true
eth-keystore = "0.5.0"
thiserror.workspace = true
eigensdk-client-avsregistry.workspace = true
ethers-providers.workspace = true
eigensdk-types.workspace = true
eigensdk-contract-bindings.workspace = true
eigensdk-crypto-bls.workspace = true
eigensdk-crypto-bn254.workspace = true
tokio.workspace = true