[package]
name = "eigensdk-metrics-collectors-rpc-calls"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
ethers-core.workspace = true
ethers.workspace = true
ethers-signers.workspace = true