[package]
name = "eigen-client-fireblocks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
# reth.workspace = true
serde.workspace = true
alloy-primitives.workspace = true