[package]
name = "eigensdk-client-avsregistry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
eigensdk-logging = {path = "../../../../crates/logging/"}
eigensdk-client-eth.workspace = true 
eigensdk-contracts-bindings = {path = "../../../../crates/contracts/bindings"}
alloy-primitives = {git = "https://github.com/alloy-rs/core", rev = "14083ea11780b92f5c6466b12cc879e3b8c16972"}
alloy-sol-types = {git = "https://github.com/alloy-rs/core", rev = "14083ea11780b92f5c6466b12cc879e3b8c16972", features = ["json"]}
alloy-contract = { git = "https://github.com/alloy-rs/alloy", rev = "818b3e9692f2a207e456653a67aa8956fe1518a9" }  # As per workspace level
alloy-provider = { git = "https://github.com/alloy-rs/alloy", rev = "818b3e9692f2a207e456653a67aa8956fe1518a9"}
alloy-network = { git = "https://github.com/alloy-rs/alloy", rev = "818b3e9692f2a207e456653a67aa8956fe1518a9"}
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy", rev = "818b3e9692f2a207e456653a67aa8956fe1518a9" }
ethers.workspace = true
serde_json = "1.0.114"
ethers-core.workspace = true
num-bigint = "0.4.4"
ethers-providers.workspace = true
eigensdk-types.workspace = true
eigensdk-crypto-bls.workspace = true
ark-ff.workspace = true
eigensdk-crypto-bn254.workspace = true
eigensdk-client-elcontracts.workspace = true
eigensdk-txmgr.workspace = true
eigensdk-chainio-utils.workspace = true


[lints]
workspace = true
