[package]
name = "eigensdk-client-avsregistry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
eigensdk-client-eth.workspace = true 
eigensdk-contracts-bindings = {path = "../../../../crates/contracts/bindings"}
alloy-primitives = "0.7.0"
ethers.workspace = true
serde_json = "1.0.114"
ethers-core.workspace = true
num-bigint = "0.4.4"
ethers-providers.workspace = true
eigensdk-types.workspace = true
eigensdk-crypto-bls.workspace = true
ark-ff.workspace = true
eigensdk-crypto-bn254.workspace = true
eigensdk-client-elcontracts.workspace = true
eigensdk-txmgr.workspace = true
eigensdk-chainio-utils.workspace = true
ark-bn254 = "0.4.0"
thiserror.workspace = true
tracing.workspace = true
tokio = {version = "1.37.0" , features = ["test-util", "full"] }
hex = "0.4.3"

[lints]
workspace = true


