[package]
name = "eigensdk-client-avsregistry"
description = "Eigen Layer AvsRegistry Sdk"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-sol-types = { workspace = true, features = ["json"] }
alloy-transport-http.workspace = true
alloy-rpc-types.workspace = true
serde_json = "1.0.114"
num-bigint = "0.4.4"
reqwest = "0.12.4"
eigensdk-types.workspace = true
eigensdk-crypto-bls.workspace = true
ark-ff.workspace = true
eigensdk-crypto-bn254.workspace = true
eigensdk-client-elcontracts.workspace = true
eigensdk-txmgr.workspace = true
eigensdk-chainio-utils.workspace = true
ark-bn254 = "0.4.0"
thiserror.workspace = true
tracing.workspace = true
tokio = {version = "1.37.0" , features = ["test-util", "full","sync"] }
hex = "0.4.3"
futures = "0.3.30"
alloy-contract.workspace = true
alloy-eips.workspace = true
[lints]
workspace = true


