[package]
name = "eigensdk-client-avsregistry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
eigensdk-client-eth.workspace = true
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
eigensdk-logging.workspace = true

[lints]
workspace = true